### ISSUE TITLE
it's not working in ios 11 i think...

### ISSUE THREAD

**Issue by xuejmnet** [judgewest2000/IonicPwa#1]
i find it's not working in ios 11 ,but when i sleep  or do something then try again it's will be working, so i'm try more times,finally i'm know  if i kill the browser process ，restart browser it will be working，because ios has sleep long times ,the process is killed，so I think the reason is this

**Comment by judgewest2000** [comment]
What’s not working?

**Comment by xuejmnet** [comment]
this project, pages/camera.html has ios11 note 
 <ion-card>
        <ion-card-header>iOS11 Note</ion-card-header>
        <ion-card-content>Currently does not work on iOS11 full screen home page links - suspect that'll get sorted out in a future update.
        </ion-card-content>
    </ion-card>

**Comment by judgewest2000** [comment]
Hi.

What version of iOS are you using?

**Comment by xuejmnet** [comment]
@judgewest2000  my phone version ios 11.4.1, when i build project, run in  browser sometimes it not working ,but kill browser process, restart browser it  will be working
